# Generated by Django 3.1.6 on 2021-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('contractor', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('supervisor', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
