# Generated by Django 3.1.6 on 2021-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0002_auto_20210625_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
