# Generated by Django 3.1.6 on 2021-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0004_auto_20210625_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='question_1',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'N/A')]),
        ),
    ]
