# Generated by Django 3.1.6 on 2021-06-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0006_auto_20210626_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='question_1',
            field=models.BooleanField(),
        ),
    ]
