# Generated by Django 3.1.6 on 2021-06-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0008_auto_20210630_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='question_1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], max_length=80),
        ),
    ]
