# Generated by Django 3.1.6 on 2021-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0011_auto_20210630_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='question_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_10',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_11',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_12',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_13',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_14',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_15',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_16',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_17',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_18',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_19',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_20',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_4',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_5',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_6',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_7',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_8',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_9',
            field=models.BooleanField(),
        ),
    ]
