# Generated by Django 3.1.6 on 2021-07-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0014_auto_20210702_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mewp',
            name='question_10',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_11',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_12',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_13',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_14',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_15',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_16',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_17',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_18',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_19',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_20',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_5',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_6',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_7',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_8',
        ),
        migrations.RemoveField(
            model_name='mewp',
            name='question_9',
        ),
    ]
