# Generated by Django 3.1.6 on 2021-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0015_auto_20210702_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='mewp',
            name='question_2',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mewp',
            name='question_1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
    ]
