# Generated by Django 3.1.6 on 2021-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0016_auto_20210702_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='mewp',
            name='question_10',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_11',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_12',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_13',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_14',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_15',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_16',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_17',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_18',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_19',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_20',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_3',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_4',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_5',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_6',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_7',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_8',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='mewp',
            name='question_9',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'NA')], default=None, max_length=3, null=True),
        ),
    ]
