# Generated by Django 3.1.6 on 2021-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewp', '0020_auto_20210910_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mewp',
            name='comments',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
